version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_hello_world
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    restart: always
