services:
  fastapi:
    image: fastapi:v1.0
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  celery_worker:
    image: celery_worker:v1.0
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    command: >
      bash -c "celery -A src.core.celery_app worker -n monitor_position_worker --concurrency=1 --loglevel=info -Q position_monitoring &
      celery -A src.core.celery_app worker -n redis_worker --concurrency=1 --loglevel=info -Q event_listener &
      celery -A src.core.celery_app worker -n notification_worker --concurrency=1 --loglevel=info -Q send_notifications &
      celery -A src.core.celery_app worker -n mainnet_challenges_worker --concurrency=1 --loglevel=info -Q monitor_mainnet_challenges &
      celery -A src.core.celery_app worker -n monitor_mainnet_worker --concurrency=1 --loglevel=info -Q monitor_miner &
      celery -A src.core.celery_app worker -n monitor_testnet_worker --concurrency=1 --loglevel=info -Q testnet_validator &
      celery -A src.core.celery_app worker -n tournament_notifications_worker --concurrency=1 --loglevel=info -Q tournament_notifications &
      celery -A src.core.celery_app worker -n processing_positions_worker --concurrency=1 --loglevel=info -Q processing_positions &
      wait -n"

  celery_beat:
    image: celery_beat:v1.0
    build:
      context: .
      dockerfile: docker/celery-beat/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    command: celery -A src.core.celery_app beat --loglevel=info

  flower:
    image: mher/flower:0.9.7
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
    command: celery flower --broker=redis://redis:6379/0 --port=5002
