import os

from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
DATABASE_URL_SYNC = os.getenv("DATABASE_URL_SYNC")
POLYGON_API_KEY = os.getenv("POLYGON_API_KEY")
POLYGON_WEBSOCKET = os.getenv("POLYGON_WEBSOCKET")
SIGNAL_API_BASE_URL = os.getenv("SIGNAL_API_BASE_URL")
SIGNAL_API_KEY = os.getenv("TRADE_API_KEY")
CHECKPOINT_URL = os.getenv("CHECKPOINT_URL")
TESTNET_CHECKPOINT_URL = os.getenv("TESTNET_CHECKPOINT_URL")
MAIN_NET = os.getenv("MAIN_NET", "false") == "true"

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# EMAIL CONFIGURATIONS
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false") == "true"
SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# EXTERNAL API
REGISTRATION_API_URL = os.getenv("REGISTRATION_API_URL")
SWITCH_TO_MAINNET_URL = os.getenv("SWITCH_TO_MAINNET_URL")
POSITIONS_URL = os.getenv("MAIN_POSITIONS_URL")
POSITIONS_TOKEN = os.getenv("MAIN_POSITIONS_TOKEN")

NEW_POSITIONS_URL = os.getenv("NEW_MAIN_POSITIONS_URL")
NEW_POSITIONS_TOKEN = os.getenv("NEW_MAIN_POSITION_TOKEN")

STATISTICS_URL = os.getenv("MAIN_STATISTICS_URL")
STATISTICS_TOKEN = os.getenv("MAIN_STATISTICS_TOKEN")

# GCP CLOUD STORAGE
GCP_PROJECT = os.getenv("GCP_PROJECT")
GCP_BUCKET = os.getenv("GCP_BUCKET")

# AWS CONFIGURATION
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_KEY")
BUCKET_NAME = os.getenv("BUCKET_NAME")

# DISCORD CONFIGURATION
WEBHOOK_URL = os.getenv("WEBHOOK_URL")
